import { mysqlTable, serial, varchar, text, boolean, datetime, int, json, mysqlEnum } from "drizzle-orm/mysql-core";

export const User = mysqlTable("users", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  username: varchar("username", { length: 255 }).notNull(),
  password: varchar("password", { length: 255 }).notNull(),
  role: mysqlEnum("role", ["USER", "ADMIN"]).default("USER").notNull(),
  unit: varchar("unit", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const SopDocument = mysqlTable("sop_documents", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  documentNumber: varchar("document_number", { length: 255 }).notNull(),
  fileUrl: varchar("file_url", { length: 255 }).notNull(),
  uploadedBy: varchar("uploaded_by", { length: 255 }).notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const OtherDocument = mysqlTable("other_documents", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  category: mysqlEnum("category", ["PEDOMAN", "PANDUAN", "KEBIJAKAN", "PROGRAM", "LAINNYA"]).notNull(),
  fileUrl: varchar("file_url", { length: 255 }).notNull(),
  uploadedBy: varchar("uploaded_by", { length: 255 }).notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const FormCuciTangan = mysqlTable("form_cuci_tangan", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  date: datetime("date").notNull(),
  officerName: varchar("officer_name", { length: 255 }).notNull(),
  profession: varchar("profession", { length: 255 }).notNull(),
  room: varchar("room", { length: 255 }).notNull(),
  moment1: boolean("moment_1").default(false),
  moment2: boolean("moment_2").default(false),
  moment3: boolean("moment_3").default(false),
  moment4: boolean("moment_4").default(false),
  moment5: boolean("moment_5").default(false),
  actionDone: boolean("action_done").default(false),
  result: varchar("result", { length: 255 }),
  createdAt: datetime("created_at"),
});

export const FormISK = mysqlTable("form_isk", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  date: datetime("date").notNull(),
  patientName: varchar("patient_name", { length: 255 }).notNull(),
  medicalRecord: varchar("medical_record", { length: 255 }).notNull(),
  catheterAction: varchar("catheter_action", { length: 255 }),
  symptoms: text("symptoms"),
  createdAt: datetime("created_at"),
});

export const FormSubmission = mysqlTable("form_submissions", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  formType: varchar("form_type", { length: 255 }).notNull(),
  formTitle: varchar("form_title", { length: 255 }).notNull(),
  data: json("data").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const FormAuditKebersihanTangan = mysqlTable("form_audit_kebersihan_tangan", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  profesi: varchar("profesi", { length: 255 }),
  namaTindakan: varchar("nama_tindakan", { length: 255 }),
  kepatuhan5Momen1SebelumKontakPasien: varchar("kepatuhan5_momen1_sebelum_kontak_pasien", { length: 255 }),
  kepatuhan5Momen2SebelumTindakanAseptik: varchar("kepatuhan5_momen2_sebelum_tindakan_aseptik", { length: 255 }),
  kepatuhan5Momen3SesudahKontakCairanPasien: varchar("kepatuhan5_momen3_sesudah_kontak_cairan_pasien", { length: 255 }),
  kepatuhan5Momen4SesudahKontakPasien: varchar("kepatuhan5_momen4_sesudah_kontak_pasien", { length: 255 }),
  kepatuhan5Momen5SesudahKontakLingkunganPasien: varchar("kepatuhan5_momen5_sesudah_kontak_lingkungan_pasien", { length: 255 }),
});

export const FormAuditFasilitasKebersihanTangan = mysqlTable("form_audit_fasilitas_kebersihan_tangan", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggalAudit: datetime("tanggal_audit"),
  auditorIpcn: varchar("auditor_ipcn", { length: 255 }),
  unitRuangan: varchar("unit_ruangan", { length: 255 }),
  handrubTersedia: varchar("handrub_tersedia", { length: 255 }),
  saranaCuciTangan: varchar("sarana_cuci_tangan", { length: 255 }),
  wastafelBerfungsi: varchar("wastafel_berfungsi", { length: 255 }),
  pengeringTangan: varchar("pengering_tangan", { length: 255 }),
  tempatSampah: varchar("tempat_sampah", { length: 255 }),
  handrubMudahDijangkau: varchar("handrub_mudah_dijangkau", { length: 255 }),
  mediaEdukasi: varchar("media_edukasi", { length: 255 }),
});

export const FormAuditKepatuhanApd = mysqlTable("form_audit_kepatuhan_apd", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  profesi: varchar("profesi", { length: 255 }),
  namaTindakan: varchar("nama_tindakan", { length: 255 }),
  kepatuhanApdSARUNGTANGAN: varchar("kepatuhan_apd_s_a_r_u_n_g_t_a_n_g_a_n", { length: 255 }),
  kepatuhanApdMASKERMEDISN95: varchar("kepatuhan_apd_m_a_s_k_e_r_m_e_d_i_s_n95", { length: 255 }),
  kepatuhanApdGOWN: varchar("kepatuhan_apd_g_o_w_n", { length: 255 }),
  kepatuhanApdTOPI: varchar("kepatuhan_apd_t_o_p_i", { length: 255 }),
  kepatuhanApdSEPATU: varchar("kepatuhan_apd_s_e_p_a_t_u", { length: 255 }),
  kepatuhanApdFACESHIELD: varchar("kepatuhan_apd_f_a_c_e_s_h_i_e_l_d", { length: 255 }),
  kepatuhanApdGOOGLES: varchar("kepatuhan_apd_g_o_o_g_l_e_s", { length: 255 }),
});

export const FormBundleIdo = mysqlTable("form_bundle_ido", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  noRm: varchar("no_rm", { length: 255 }),
  preOperasiCukurDenganEClipperHanyaPadaAreaOperasi: varchar("pre_operasi_cukur_dengan_e_clipper_hanya_pada_area_operasi", { length: 255 }),
  preOperasiWaktuCukur2JamSebelumOperasi: varchar("pre_operasi_waktu_cukur2_jam_sebelum_operasi", { length: 255 }),
  preOperasiMandiChlorhexidine: varchar("pre_operasi_mandi_chlorhexidine", { length: 255 }),
  preOperasiAntibiotikProfilaksis1JamSebelumInsisi: varchar("pre_operasi_antibiotik_profilaksis1_jam_sebelum_insisi", { length: 255 }),
  preOperasiPasienTidakSedangInfeksi: varchar("pre_operasi_pasien_tidak_sedang_infeksi", { length: 255 }),
  preOperasiGulaDarah200GrDl: varchar("pre_operasi_gula_darah200_gr_dl", { length: 255 }),
  preOperasiSuhuTubuhNormal: varchar("pre_operasi_suhu_tubuh_normal", { length: 255 }),
  intraOperasiPetugasMelakukanCuciTanganBedah: varchar("intra_operasi_petugas_melakukan_cuci_tangan_bedah", { length: 255 }),
  intraOperasiInstrumenSteril: varchar("intra_operasi_instrumen_steril", { length: 255 }),
  intraOperasiDisinfeksiPermukaanKulitAreaOperasiSesuaiStandar: varchar("intra_operasi_disinfeksi_permukaan_kulit_area_oper_199e2", { length: 255 }),
  intraOperasiStrictPersonilPembatasanPetugas: varchar("intra_operasi_strict_personil_pembatasan_petugas", { length: 255 }),
  intraOperasiLingkunganOKSuhuDanKelembabanTerstandar: varchar("intra_operasi_lingkungan_o_k_suhu_dan_kelembaban_terstandar", { length: 255 }),
  postOperasiRawatLukaTeknikSterilDenganCairanNaCl: varchar("post_operasi_rawat_luka_teknik_steril_dengan_cairan_na_cl", { length: 255 }),
  postOperasiLukaDitutup2448JamAtauDibukaSetelahPOD2KecualiBilaAdaRembesanAtauInfeksi: varchar("post_operasi_luka_ditutup2448_jam_atau_dibuka_sete_109f2", { length: 255 }),
  postOperasiNutrisiSesuaiKebutuhan: varchar("post_operasi_nutrisi_sesuai_kebutuhan", { length: 255 }),
  postOperasiKontrolGulaDarah: varchar("post_operasi_kontrol_gula_darah", { length: 255 }),
  postOperasiTidakAdaPerpanjanganAB: varchar("post_operasi_tidak_ada_perpanjangan_a_b", { length: 255 }),
});

export const FormBundleVap = mysqlTable("form_bundle_vap", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  noRm: varchar("no_rm", { length: 255 }),
  namaPasien: varchar("nama_pasien", { length: 255 }),
  insersiKebersihanTangan: varchar("insersi_kebersihan_tangan", { length: 255 }),
  insersiTeknikSteril: varchar("insersi_teknik_steril", { length: 255 }),
  insersiPemakaianAPD: varchar("insersi_pemakaian_a_p_d", { length: 255 }),
  insersiSedasi: varchar("insersi_sedasi", { length: 255 }),
  maintenanceKebersihanTangan: varchar("maintenance_kebersihan_tangan", { length: 255 }),
  maintenancePosisiPasien3040Derajat: varchar("maintenance_posisi_pasien3040_derajat", { length: 255 }),
  maintenanceKebersihanMulutSetiap4JamKP: varchar("maintenance_kebersihan_mulut_setiap4_jam_k_p", { length: 255 }),
  maintenanceManagemenSekresiOropharingeal: varchar("maintenance_managemen_sekresi_oropharingeal", { length: 255 }),
  maintenanceProsedurSedasiDanAnalgetik: varchar("maintenance_prosedur_sedasi_dan_analgetik", { length: 255 }),
});

export const FormBundlePlabsi = mysqlTable("form_bundle_plabsi", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  noRm: varchar("no_rm", { length: 255 }),
  namaPasien: varchar("nama_pasien", { length: 255 }),
  insersiPemilihanLokasi: varchar("insersi_pemilihan_lokasi", { length: 255 }),
  insersiKebersihanTangan: varchar("insersi_kebersihan_tangan", { length: 255 }),
  insersiPreparasiKulitAlkoholChg: varchar("insersi_preparasi_kulit_alkohol_chg", { length: 255 }),
  insersiMaximumAPD: varchar("insersi_maximum_a_p_d", { length: 255 }),
  maintenanceReviewSetiapHari: varchar("maintenance_review_setiap_hari", { length: 255 }),
  maintenanceKebersihanTangan: varchar("maintenance_kebersihan_tangan", { length: 255 }),
  maintenanceDisenfeksiHub: varchar("maintenance_disenfeksi_hub", { length: 255 }),
  maintenancePergantianDresing: varchar("maintenance_pergantian_dresing", { length: 255 }),
  maintenancePergantianSetAdministrasi: varchar("maintenance_pergantian_set_administrasi", { length: 255 }),
});

export const FormBundleCauti = mysqlTable("form_bundle_cauti", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  noRm: varchar("no_rm", { length: 255 }),
  namaPasien: varchar("nama_pasien", { length: 255 }),
  insersiKajiKebutuhan: varchar("insersi_kaji_kebutuhan", { length: 255 }),
  insersiPemasanganOlehPetugasTerlatih: varchar("insersi_pemasangan_oleh_petugas_terlatih", { length: 255 }),
  insersiKebersihanTangan: varchar("insersi_kebersihan_tangan", { length: 255 }),
  insersiTeknikSteril: varchar("insersi_teknik_steril", { length: 255 }),
  maintenanceKebersihanTangan: varchar("maintenance_kebersihan_tangan", { length: 255 }),
  maintenancePerawatanKateter: varchar("maintenance_perawatan_kateter", { length: 255 }),
  maintenancePemilihanKateter: varchar("maintenance_pemilihan_kateter", { length: 255 }),
  maintenanceSegeraLepasJikaTidakDibutuhkanLagi: varchar("maintenance_segera_lepas_jika_tidak_dibutuhkan_lagi", { length: 255 }),
});

export const FormMonitoringIpal = mysqlTable("form_monitoring_ipal", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggalMonitoring: datetime("tanggal_monitoring"),
  namaPetugasAudit: varchar("nama_petugas_audit", { length: 255 }),
  namaPetugasIpal: varchar("nama_petugas_ipal", { length: 255 }),
  lingkunganIpal: varchar("lingkungan_ipal", { length: 255 }),
  bakIndikator: varchar("bak_indikator", { length: 255 }),
  prosesBiologis: varchar("proses_biologis", { length: 255 }),
  alatPemantau: varchar("alat_pemantau", { length: 255 }),
  pengolahanAir: varchar("pengolahan_air", { length: 255 }),
  sistemPembuangan: varchar("sistem_pembuangan", { length: 255 }),
  mesinBlower: varchar("mesin_blower", { length: 255 }),
  pemantauanDebit: varchar("pemantauan_debit", { length: 255 }),
  pemeriksaanMutu: varchar("pemeriksaan_mutu", { length: 255 }),
  petugasApd: varchar("petugas_apd", { length: 255 }),
  saranaHigiene: varchar("sarana_higiene", { length: 255 }),
});

export const FormAuditPembuanganLimbah = mysqlTable("form_audit_pembuangan_limbah", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  namaPetugasAudit: varchar("nama_petugas_audit", { length: 255 }),
  unitRuangan: varchar("unit_ruangan", { length: 255 }),
  pemilahan: varchar("pemilahan", { length: 255 }),
  wadahLimbah: varchar("wadah_limbah", { length: 255 }),
  safetyBox: varchar("safety_box", { length: 255 }),
  kantongLimbah: varchar("kantong_limbah", { length: 255 }),
  petugasApd: varchar("petugas_apd", { length: 255 }),
  pengangkutan: varchar("pengangkutan", { length: 255 }),
  tidakAdaTumpahan: varchar("tidak_ada_tumpahan", { length: 255 }),
  penyimpananSementara: varchar("penyimpanan_sementara", { length: 255 }),
  pembuanganAkhir: varchar("pembuangan_akhir", { length: 255 }),
});

export const FormAuditLinenKotor = mysqlTable("form_audit_linen_kotor", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  segeraAmbil: varchar("segera_ambil", { length: 255 }),
  laundryAmbil: varchar("laundry_ambil", { length: 255 }),
  tempatSesuai: varchar("tempat_sesuai", { length: 255 }),
  masukBakBenar: varchar("masuk_bak_benar", { length: 255 }),
  fasilitasBak: varchar("fasilitas_bak", { length: 255 }),
  plastikTersedia: varchar("plastik_tersedia", { length: 255 }),
  ambilSesuaiJadwal: varchar("ambil_sesuai_jadwal", { length: 255 }),
  trollyKhusus: varchar("trolly_khusus", { length: 255 }),
});

export const FormAuditBendaTajam = mysqlTable("form_audit_benda_tajam", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  injeksiLangsung: varchar("injeksi_langsung", { length: 255 }),
  canulaDisimpan: varchar("canula_disimpan", { length: 255 }),
  bendaTajamMasuk: varchar("benda_tajam_masuk", { length: 255 }),
  safetyBoxTidakLebih: varchar("safety_box_tidak_lebih", { length: 255 }),
  safetyBoxBersih: varchar("safety_box_bersih", { length: 255 }),
  safetyBoxTertutup: varchar("safety_box_tertutup", { length: 255 }),
});

export const FormAuditLimbahCair = mysqlTable("form_audit_limbah_cair", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  ipcn: varchar("ipcn", { length: 255 }),
  ruangan: varchar("ruangan", { length: 255 }),
  cuciTanganSebelum: varchar("cuci_tangan_sebelum", { length: 255 }),
  apdMinimal: varchar("apd_minimal", { length: 255 }),
  dibuangSpoelhock: varchar("dibuang_spoelhock", { length: 255 }),
  disiramAir: varchar("disiram_air", { length: 255 }),
  apdDilepas: varchar("apd_dilepas", { length: 255 }),
  cuciTanganSesudah: varchar("cuci_tangan_sesudah", { length: 255 }),
});

export const FormMonitoringKamarJenazah = mysqlTable("form_monitoring_kamar_jenazah", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  waktu: varchar("waktu", { length: 255 }),
  namaPetugasAuditor: varchar("nama_petugas_auditor", { length: 255 }),
  kondisiKebersihan: varchar("kondisi_kebersihan", { length: 255 }),
  lantaiKering: varchar("lantai_kering", { length: 255 }),
  ventilasi: varchar("ventilasi", { length: 255 }),
  ketersediaanApd: varchar("ketersediaan_apd", { length: 255 }),
  petugasApd: varchar("petugas_apd", { length: 255 }),
  fasilitasCuciTangan: varchar("fasilitas_cuci_tangan", { length: 255 }),
  penangananSop: varchar("penanganan_sop", { length: 255 }),
  pembersihanDesinfeksi: varchar("pembersihan_desinfeksi", { length: 255 }),
  pengelolaanLinen: varchar("pengelolaan_linen", { length: 255 }),
  tempatSampahKlasifikasi: varchar("tempat_sampah_klasifikasi", { length: 255 }),
  safetyBoxTersedia: varchar("safety_box_tersedia", { length: 255 }),
  sopTersedia: varchar("sop_tersedia", { length: 255 }),
});

export const FormLaporanTertusukJarum = mysqlTable("form_laporan_tertusuk_jarum", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  namaPetugas: varchar("nama_petugas", { length: 255 }),
  nipNoPegawai: varchar("nip_no_pegawai", { length: 255 }),
  unitInstalasi: varchar("unit_instalasi", { length: 255 }),
  jabatan: varchar("jabatan", { length: 255 }),
  tanggalKejadian: datetime("tanggal_kejadian"),
  waktuKejadian: varchar("waktu_kejadian", { length: 255 }),
  lokasiKejadian: varchar("lokasi_kejadian", { length: 255 }),
  jenisPajanan: varchar("jenis_pajanan", { length: 255 }),
  bendaPenyebab: varchar("benda_penyebab", { length: 255 }),
  bagianTubuh: varchar("bagian_tubuh", { length: 255 }),
  kronologiSingkat: text("kronologi_singkat"),
  tindakanPertama: varchar("tindakan_pertama", { length: 255 }),
  menggunakanApd: varchar("menggunakan_apd", { length: 255 }),
  statusPasienSumber: varchar("status_pasien_sumber", { length: 255 }),
  pemeriksaanLab: varchar("pemeriksaan_lab", { length: 255 }),
  tanggalPemeriksaan: datetime("tanggal_pemeriksaan"),
  jenisPemeriksaanPetugas: varchar("jenis_pemeriksaan_petugas", { length: 255 }),
  hasilPemeriksaanPetugas: varchar("hasil_pemeriksaan_petugas", { length: 255 }),
  jenisPemeriksaanPasien: varchar("jenis_pemeriksaan_pasien", { length: 255 }),
  hasilPemeriksaanPasien: varchar("hasil_pemeriksaan_pasien", { length: 255 }),
});

export const FormMonitoringLinenLaundry = mysqlTable("form_monitoring_linen_laundry", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  tanggal: datetime("tanggal"),
  namaAuditor: varchar("nama_auditor", { length: 255 }),
  namaPetugasLaundry: varchar("nama_petugas_laundry", { length: 255 }),
  b1Dipisahkan: varchar("b1_dipisahkan", { length: 255 }),
  b2Infeksius: varchar("b2_infeksius", { length: 255 }),
  b3KantongKhusus: varchar("b3_kantong_khusus", { length: 255 }),
  b4PetugasApd: varchar("b4_petugas_apd", { length: 255 }),
  b5TidakDiLantai: varchar("b5_tidak_di_lantai", { length: 255 }),
  c1TroliTersedia: varchar("c1_troli_tersedia", { length: 255 }),
  c2TroliTertutup: varchar("c2_troli_tertutup", { length: 255 }),
  c3TransportTerpisah: varchar("c3_transport_terpisah", { length: 255 }),
  d1AreaTerpisah: varchar("d1_area_terpisah", { length: 255 }),
  d2MesinCuci: varchar("d2_mesin_cuci", { length: 255 }),
  d3Deterjen: varchar("d3_deterjen", { length: 255 }),
  d4Desinfektan: varchar("d4_desinfektan", { length: 255 }),
  d5PetugasApd: varchar("d5_petugas_apd", { length: 255 }),
  e1Dryer: varchar("e1_dryer", { length: 255 }),
  e2TidakMenyentuhLantai: varchar("e2_tidak_menyentuh_lantai", { length: 255 }),
  e3AreaBersih: varchar("e3_area_bersih", { length: 255 }),
  f1AreaBersih: varchar("f1_area_bersih", { length: 255 }),
  f2RakTertutup: varchar("f2_rak_tertutup", { length: 255 }),
  f3TroliDistribusi: varchar("f3_troli_distribusi", { length: 255 }),
  f4TerlindungDebu: varchar("f4_terlindung_debu", { length: 255 }),
});

export const FormPretestEdukasiGizi = mysqlTable("form_pretest_edukasi_gizi", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
  namaLengkap: varchar("nama_lengkap", { length: 255 }),
  asalInstitusi: varchar("asal_institusi", { length: 255 }),
  tanggalPengisian: datetime("tanggal_pengisian"),
  soal1: varchar("soal1", { length: 255 }),
  soal2: varchar("soal2", { length: 255 }),
  soal3: varchar("soal3", { length: 255 }),
  soal4: varchar("soal4", { length: 255 }),
  soal5: varchar("soal5", { length: 255 }),
});

export const FormInsidenHais = mysqlTable("form_insiden_hais", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  tanggal: datetime("tanggal").notNull(),
  namaPasien: varchar("nama_pasien", { length: 255 }).notNull(),
  noRm: varchar("no_rm", { length: 255 }).notNull(),
  ruangan: varchar("ruangan", { length: 255 }).notNull(),
  jenisInsiden: varchar("jenis_insiden", { length: 255 }).notNull(),
  tindakanInvasif: varchar("tindakan_invasif", { length: 255 }),
  gejala: text("gejala"),
  createdAt: datetime("created_at"),
});

export const FormLogbookIpcn = mysqlTable("form_logbook_ipcn", {
  id: serial("id").primaryKey(),
  userId: int("user_id").notNull(),
  date: datetime("date").notNull(),
  ipcnName: varchar("ipcn_name", { length: 255 }).notNull(),
  room: varchar("room", { length: 255 }).notNull(),
  activityType: varchar("activity_type", { length: 255 }).notNull(),
  description: text("description").notNull(),
  findings: text("findings"),
  followUp: text("follow_up"),
  followUpStatus: varchar("follow_up_status", { length: 255 }),
  proofUrl: varchar("proof_url", { length: 255 }),
  createdAt: datetime("created_at"),
});

export const Ipcn = mysqlTable("ipcn", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const Ruangan = mysqlTable("ruangan", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

export const Profesi = mysqlTable("profesi", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  createdAt: datetime("created_at"),
  updatedAt: datetime("updated_at").notNull(),
});

